# Generated by Django 5.2.13 on 2026-05-23 20:50

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_adventure_access_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('point_count', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('place_name', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='running', max_length=20)),
                ('processed', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('visits_added', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adventure',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adventures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='tracker.device'),
        ),
        migrations.AlterField(
            model_name='adventureblurb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_blurbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adventureblurbphoto',
            name='image',
            field=models.ImageField(upload_to='adventures/blurbs/'),
        ),
        migrations.AlterField(
            model_name='adventureblurbphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='adventures/blurbs/thumbs/'),
        ),
        migrations.AlterField(
            model_name='adventurecomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adventure_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adventuremember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adventuremilestone',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='location',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='tracker_loc_location_gist'),
        ),
        migrations.AddField(
            model_name='visit',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tracker.device'),
        ),
        migrations.AddField(
            model_name='visit',
            name='poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='tracker.poi'),
        ),
        migrations.AddField(
            model_name='visitjob',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit_job', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['device', '-start_time'], name='tracker_vis_device__idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['city'], name='tracker_vis_city_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['poi'], name='tracker_vis_poi_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='tracker_vis_location_gist'),
        ),
    ]
