# Generated by Django 5.2.13 on 2026-05-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_sitestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestat',
            name='total_meters',
            field=models.BigIntegerField(default=0),
        ),
    ]
