# This migration was auto-generated by a host-side Django installation (6.0.5)
# against an old models.py image and incorrectly removed fields added by 0017.
# It is preserved here only because it was already applied to the database.
# Migration 0020 re-adds everything this migration removed.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_adventure_body_from_blurbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='body',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='cover_image_thumbnail',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='adventureblurb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adventuremilestone',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
