"""
Corrective migration: 0019 was auto-generated by the Docker entrypoint running
makemigrations against an old models.py image before the container was rebuilt.
It incorrectly removed the fields added in 0017. This migration re-adds them.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_remove_adventure_body_remove_adventure_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='subtitle',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='adventure',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='adventures/covers/'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='cover_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='adventures/covers/thumbs/'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='body',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='adventureblurb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='adventuremilestone',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
