# Generated by Django 6.0.7 on 2026-07-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0053_roaddownloadjob_worker_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaddownloadjob',
            name='worker_token',
        ),
    ]
