# Generated by Django 6.1 on 2026-08-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0068_downloaded_region_auto_download'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='downloadedregion',
            new_name='tracker_dow_kind_9ff204_idx',
            old_name='tracker_downloadedregion_kind_idx',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('login_fail', 'Login failed'), ('error', 'Server error'), ('import', 'Import data'), ('delete_data', 'Delete location data'), ('delete_account', 'Delete account'), ('admin_toggle', 'Admin toggle'), ('admin_delete_user', 'Admin deleted user'), ('custom_js_save', 'Custom JS saved'), ('api_key_create', 'API key created'), ('api_key_delete', 'API key deleted'), ('totp_enable', 'TOTP enabled'), ('totp_disable', 'TOTP disabled'), ('totp_regen_backup', 'TOTP backup codes regenerated'), ('other', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='totpbackupcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
